# This file sets up the path for the H2 schema in Section 11
spring.application.name=demo
spring.sql.init.schema-locations=classpath:Section11/schema.sql
spring.sql.init.data-locations=classpath:Section11/data.sql

# This section allows to configure PostgreSQL to use in SpringJDBC
# You have to mention the IP server address and the server port number
# Connection URL Format: jdbc:postgresql://hostname:port/database_name
# hostname: server address (localhost for local machine)
# port: PostgreSQL port (default: 5432)
# database_name: name of your database
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

